<div class="flex flex-col gap-4">
<div><label class="mb-1.5 block font-mono text-[11px] uppercase tracking-[0.18em] text-muted">Service name</label><input name="service_name" value="{{ old('service_name', $service->service_name ?? '') }}" required class="h-11 w-full rounded-md border border-line-strong bg-white px-3 text-sm focus:border-ink focus:outline-none"></div>
<div class="grid grid-cols-3 gap-4">
<div><label class="mb-1.5 block font-mono text-[11px] uppercase tracking-[0.18em] text-muted">Price Rp</label><input name="price_per_unit" type="number" min="0" value="{{ old('price_per_unit', $service->price_per_unit ?? '') }}" required class="h-11 w-full rounded-md border border-line-strong bg-white px-3 font-mono text-sm focus:border-ink focus:outline-none"></div>
<div><label class="mb-1.5 block font-mono text-[11px] uppercase tracking-[0.18em] text-muted">Unit</label><select name="unit_type" class="h-11 w-full rounded-md border border-line-strong bg-white px-3 text-sm"><option value="kg" @selected(old('unit_type', $service->unit_type ?? '') === 'kg')>per kg</option><option value="pcs" @selected(old('unit_type', $service->unit_type ?? '') === 'pcs')>per pcs</option></select></div>
<div><label class="mb-1.5 block font-mono text-[11px] uppercase tracking-[0.18em] text-muted">Hours</label><input name="estimated_hours" type="number" min="1" max="720" value="{{ old('estimated_hours', $service->estimated_hours ?? 24) }}" required class="h-11 w-full rounded-md border border-line-strong bg-white px-3 font-mono text-sm focus:border-ink focus:outline-none"></div>
</div>
<div><label class="mb-1.5 block font-mono text-[11px] uppercase tracking-[0.18em] text-muted">Promo (optional)</label><select name="promo_id" class="h-11 w-full rounded-md border border-line-strong bg-white px-3 text-sm focus:border-ink focus:outline-none"><option value="">- none -</option>@foreach($promos as $p)<option value="{{ $p->id }}" @selected((string) old('promo_id', isset($service) ? ($service->promos->first()?->id ?? '') : '') === (string) $p->id)>{{ $p->name }} -{{ $p->percent }}% (min {{ $p->min_qty }}{{ $p->min_unit }})</option>@endforeach</select></div>
</div>
